version: '2'
services:

  katalog:
      container_name: external
      image: mista123/external-rso:latest
      networks:
        - net
      ports:
        - 8089:8089
      environment:
        - db_user=postgres
        - db_pw=postgres

volumes:
  image-db:
    driver: local

networks:
  net:
    driver: bridge